apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx

data:
  log-format-upstream: '{"time":"$time_iso8601","remote_addr":"$remote_addr","x_forwarded_for":"$proxy_add_x_forwarded_for","request_id":"$req_id","remote_user":"$remote_user","bytes_sent":$bytes_sent,"request_time":$request_time,"status":$status,"host":"$host","protocol":"$server_protocol","uri":"$uri","request":"$request","request_method":"$request_method","referer":"$http_referer","user_agent":"$http_user_agent","upstream_addr":"$upstream_addr","upstream_response_time":"$upstream_response_time","upstream_status":"$upstream_status","namespace":"$namespace","ingress_name":"$ingress_name","service_name":"$service_name","service_port":"$service_port"}'
