apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  accessMode: "rwx"
  nfsOptions: "nfsvers=4.1"
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
