apiVersion: apps/v1
kind: Deployment
metadata:
  name: matnn
spec:
  template:
    spec:
      containers:
        - name: matnn
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
                #limits:
                #  memory: 256Mi
                #requests:
                #  memory: 64Mi
